version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
  settings:
    errcheck:
      check-type-assertions: true

linters-settings:
  gofumpt:
    # Use gofumpt formatting which includes modern Go style preferences
    lang-version: "1.24"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
